# config.toml

[units]
infantry = { attack = 5, defense = 5, cost = 10 }
tank = { attack = 10, defense = 8, cost = 20 }
artillery = { attack = 15, defense = 5, cost = 25 }

[max_forces_per_turn]
max = 150
