bonus_turn = 3
max_water_province_percentage = 30
max_grid_size = 30

[army]
infantry = { attack = 1, defense = 1, rarity = 50 }
cavalry = { attack = 2, defense = 1, rarity = 30 }
artillery = { attack = 3, defense = 2, rarity = 20 }
tank = { attack = 5, defense = 4, rarity = 10 }
