# config.toml

[army]
# Define different types of army units with their attributes
# Attack: the attack power of the unit
# Defense: the defense power of the unit
# Rarity: the chance of obtaining the unit, higher number means less likely

[army.Soldier]
attack = 5
defense = 5
rarity = 70

[army.Archer]
attack = 7
defense = 3
rarity = 50

[army.Knight]
attack = 10
defense = 8
rarity = 30

[army.Mage]
attack = 12
defense = 4
rarity = 20

[army.Dragon]
attack = 20
defense = 15
rarity = 5
