bonus_turn = 2
max_water_province_percentage = 20
max_grid_size = 20

[[units]]
name = "Infantry"
attack = 5
defense = 3
rarity = 50

[[units]]
name = "Cavalry"
attack = 7
defense = 4
rarity = 30

[[units]]
name = "Artillery"
attack = 10
defense = 2
rarity = 20
