[game]
bonus_turn = 2
max_water_province_percentage = 30
max_grid_size = 20

[[units]]
name = "Soldier"
attack = 10
defense = 5
rarity = 50

[[units]]
name = "Tank"
attack = 50
defense = 20
rarity = 30

[[units]]
name = "Jet"
attack = 80
defense = 10
rarity = 20
